travis:
  secure:
    BINSTAR_TOKEN: fHV/KLUqAkPTmbZ/sLffu4XcrrYcUAoIMoCU6yi8PQc1I3Gx1YiYrim0oiO/dR1ViY+FKsryPEfrkNdLDBx0/vVdYT4UNL4+1DMN2P1YCMs25IKvOQ2cDCRhf4cET/Klx7iMHy+mjGhuyIaShh3Q0McnSkrVPrPKVqxRnJuImp2JLICxb5pND0+O8Fz5PYDzbl6jxpGQWtChLhrZngSZasn4MRF5PK/ceItYNeAjQUlc/TTm6OQyXujcnBIaJfC2zsxBND+5tf/B4ESXoTjZPR+lVP+DJN7Hgzclx4ibDiXOrs6v9S61O6zyJ4RxnvH0rirf8V/2BuxBITx4puGHqdZNDDJx8LfG7TvvxWNCbrNRMRlC6zpMOrYsNT+ONF5Zt4116PGxQ1pce/FiZ2ZExVGYnmMmGDmuvRzjiVa5jUxPm30EOBNKBS4ZyK7TjO+whexWLcUAkKAZowMgFdnT6lTOl8tt3jhGzkydw7ssEz5uFelG1uQEB2CA5hgGChbsjhc2pVqirj5FbLJ3jW/OY4w3sCEKqRipDQdceHgCxhIRXSsgxUHYQcX4eNRgYSV4NSZJQwz//LYzYAcx5OFU4xqubPxDxGsPQxO+Urc1HV7eDy4OEq1bNDWb3igMP8zFPnljfzVEIJQ8fva7BOORbYwaNap0+0MA8jbt3+oK8BY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
