travis:
  secure:
    BINSTAR_TOKEN: W4C+yiVb6Sb5/LySqsqCaMepo1WABj9ddsX8Um7YLukYf0w8RI/qZUTLqdZFkJfK4KWoGhJo7j6YicBw9rDhgINTuL/dBm1xFW718iu2nXtQfBESJ2LJj7kNesPazSiHxRT9gUwejLfPkuv2InB3QhnUeEpBvB1dHRxXaCnUtEMCJ35KprON/4SFNMAjhHIIzudmlSBoMhnYiaIavgWgAfMuSIMdZ956U7aVvCxUzg9nQGLLWIx11MzFGaQYCSVu/5iuOP8yUBRj+mdRbX7vMW1t6eVUr6JR5UR0eg6IFrlWgquOdadNuayPD9z6E1g7TgV+c799oBOsRMZUPdFwxnWvORlB3gW0gZuRxwBUCH+sQdO88sfRDgTVz+vnRJWaQ62HVFMDeylCGGLjONyqk68p1HmdMDcDIF+LfICEwhlLtp2oiJVndCci9f+rnDH4lpTINy7g7a4KxOALtIvRdi/h/Ju3AJyt2CayuKKxMOEtuD9rxdn/wrY90A/YOsRgnwR5GgFKV8O4eMVbTSsE1G60iUvvWWqVH/7mrONAxQhgNZoMW+IDnfFzV/Ul8uQQJaAIpSTyuO/WLhT6KNpySb0r7xXgLLl5ksdcEHjQQhokB/H6s3aPrGdLy9rOB/DqpthCWoHeABAB3uzmGwmsX9G1yq7+48bruaHKcePAUAU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
